-- Optimized Supabase Schema for PWA Performance

-- 1. Profiles Table (Auth Sync)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'Staff',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies (Optimized)
CREATE POLICY "Public profiles are viewable by everyone" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- 2. Invoices Table
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  date DATE NOT NULL,
  customer_name TEXT,
  customer_phone TEXT,
  customer_address TEXT,
  items JSONB,
  subtotal DECIMAL(12,2),
  discount DECIMAL(12,2),
  tax DECIMAL(12,2),
  total DECIMAL(12,2),
  paid_amount DECIMAL(12,2),
  remaining_amount DECIMAL(12,2),
  payment_method TEXT,
  status TEXT,
  time TEXT,
  previous_remaining DECIMAL(12,2),
  user_id UUID REFERENCES auth.users,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for fast querying
CREATE INDEX IF NOT EXISTS idx_invoices_number ON invoices(invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(date);
CREATE INDEX IF NOT EXISTS idx_invoices_user ON invoices(user_id);

-- 3. Purchases Table
CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT,
  supplier_name TEXT,
  supplier_phone TEXT,
  supplier_address TEXT,
  date DATE NOT NULL,
  items JSONB,
  total DECIMAL(12,2),
  total_cost DECIMAL(12,2),
  discount DECIMAL(12,2),
  tax DECIMAL(12,2),
  paid_amount DECIMAL(12,2),
  remaining_amount DECIMAL(12,2),
  payment_method TEXT,
  status TEXT,
  time TEXT,
  previous_remaining DECIMAL(12,2),
  subtotal DECIMAL(12,2),
  user_id UUID REFERENCES auth.users,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for fast querying
CREATE INDEX IF NOT EXISTS idx_purchases_number ON purchases(invoice_number);
CREATE INDEX IF NOT EXISTS idx_purchases_date ON purchases(date);
CREATE INDEX IF NOT EXISTS idx_purchases_user ON purchases(user_id);

-- Enable RLS for all tables
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;

-- Optimized RLS Policies (Allow all for authenticated users, scoped by user_id if needed)
-- For a pharmacy app, usually all staff can see all invoices, but we can restrict if needed.
CREATE POLICY "Authenticated users can read invoices" ON invoices FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert invoices" ON invoices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update invoices" ON invoices FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can read purchases" ON purchases FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert purchases" ON purchases FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update purchases" ON purchases FOR UPDATE TO authenticated USING (true);

-- Function to handle profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role, status)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, 'Staff', 'active');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for profile creation
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
